### ISSUE TITLE
Flights are all at 1:50AM

### ISSUE THREAD

**Issue by glenpogz36** [Zizzs/cshtml-Airline-Planner#1]

**Comment by LeilaniL** [comment]
To reproduce error:
-Run project
-Search flights by "Seattle"
-See search results (at http://localhost:5000/flight/search)

"Flight List
Seattle to Austin - Departure Time: 12/04/2018 1:50 AM
Seattle to Suquamish - Departure Time: 12/04/2018 1:50 AM
Seattle to New York - Departure Time: 12/04/2018 1:50 AM
Seattle to Honolulu - Departure Time: 12/04/2018 1:50 AM"

All the dates and times are the same.
Seattle to Suquamish should be 12/11/2018 12:12 AM

**Comment by Zizzs** [comment]
Thanks Leilani!
